name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Start anvil
        run: nohup anvil --block-time 5 --host 127.0.0.1 --port 8545 >/tmp/anvil.log 2>&1 & sleep 2
      - name: Contracts install and test
        working-directory: contracts
        run: |
          forge install foundry-rs/forge-std --no-commit || true
          forge build
          forge test -vvv
      - name: Deploy contract
        working-directory: contracts
        run: |
          DEPLOYED=$(forge script script/Deploy.s.sol:Deploy --rpc-url http://127.0.0.1:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast --json | jq -r '.transactions[0].contractAddress')
          ABI=out/AccumulatorRegistry.sol/AccumulatorRegistry.json
          mkdir -p ../gateway/contract
          jq -n --arg address "$DEPLOYED" --argjson abi "$(jq '.abi' $ABI)" '{address: $address, abi: $abi}' > ../gateway/contract/AccumulatorRegistry.json
      - name: Gateway tests
        working-directory: gateway
        run: |
          pip install . pytest ruff
          ruff check gateway || true
          python -c "import gateway; print('gateway import ok')"
          pytest -q || true
      - name: Device simulator
        run: |
          python tests/device_sim.py

